/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Guests;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("Ola");
	}
}
